# Generated by Django 2.2.2 on 2019-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_final',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicial',
            field=models.DateTimeField(),
        ),
    ]
