# Generated by Django 2.2.2 on 2019-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190620_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
