# Generated by Django 2.2.2 on 2019-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190620_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_evento'),
        ),
    ]
