# Generated by Django 2.2.2 on 2019-06-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190621_0515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Evento',
            new_name='Tipo',
        ),
    ]
